project:
  type: website
  output-dir: docs

website:
  title: "Rania Abdul Hafiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mini_project1B.qmd
      - interactive_maps_github.qmd
      - mini_project2.qmd
      - mini_project4.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

